media: images

content:
 - name: post
   label: Post
   path: _posts
   type: collection
   fields:
    - name: layout
      label: Layout
      type: string
      default: post
    - name: title
      label: Title
      type: string
    - name: date
      type: date
    - name: categories
      label: Categories
      type: select
      options:
        values: [ choice ]
        